### ISSUE TITLE
Smoke tests for elk eval command

### ISSUE THREAD

**Issue by norabelrose** [EleutherAI/elk#186]
Currently we have smoke tests for elk elicit but not elk eval

**Comment by thejaminator** [comment]
I am the test master!

**Comment by ChristyKoh** [comment]
I'd like to learn to write tests too!

**Comment by thejaminator** [comment]
> I'd like to learn to write tests too!

Hey @ChristyKoh! 

n all seriousness, you can go ahead and try writing them, there's an existing smoke test for elicit that you can follow. The smoke test currently simply checks for files being created - it's quite simple. 
I'll be busy applying for SERIMATS these two days so ill probably only get started later anyways. So you can ping me and i can help to review your PR once it's ready

**Comment by derpyplops** [comment]
Fixed and closed by #204
