### ISSUE TITLE
Use better filenames for the pkls so they don't get overwritten

### ISSUE THREAD

**Issue by QuintinPope** [EleutherAI/elk#35]

**Comment by FabienRoger** [comment]
I suggest passing a "run name" as argument to avoid having super long file names specifying every single parameter of the runs. The run name would prefix both the pkl file names & the results csv files.

Is there a better third option? Or do people usually eat the super long file names to avoid having to track how they called their runs? (The full parameters and metadata of each run would be saved in a json file).
