### ISSUE TITLE
Enable multi-class classification

### ISSUE THREAD

**Issue by FabienRoger** [EleutherAI/elk#6]
This is maybe a change too big and cumbersome to be worth implementing, because it means tensors will be replaced by lists of tensor of different shapes (because each dataset doesn't have the same number of labels, which is precisely the point of using multi-class classification).

**Comment by norabelrose** [comment]
I actually think this is worth implementing after my realization that you could do this in a mathematically elegant way by penalizing the squared log normalizer. That said we need to think carefully about how to code it

**Comment by norabelrose** [comment]
This was solved months ago
