### ISSUE TITLE
Object-oriented loss API

### ISSUE THREAD

**Issue by norabelrose** [EleutherAI/elk#62]
Loss functions should probably be modules, like `nn.BCELoss` and friends. Instead of passing loss kwargs directly to the `CCS` constructor, we would pass a loss object to `CCS.fit()` and perhaps also `CCS.score()`.

**Comment by mariopenglee** [comment]
I'd be interesting in doing this if no one else is doing it, I can probably get it done by tomorrow

**Comment by norabelrose** [comment]
Solved by #111
