### ISSUE TITLE
Parallelize probe training across layers

### ISSUE THREAD

**Issue by norabelrose** [EleutherAI/elk#64]
Instead of using `torch.distributed` to paralleize probe training, we can simply create a `multiprocessing.Queue` with one worker per GPU, and train the probes for each layer of a transformer in parallel.

**Comment by norabelrose** [comment]
To be clear: a fix for this issue should remove all the vestigial calls to `torch.distributed` in the training code. It's not actually needed if we go this route.

**Comment by anshradh** [comment]
I'd be interested in picking this up! Is there a preferred timeframe in which this gets done? My guess is that I could probably finish this over the coming weekend, but if that's not soon enough probably someone else should tackle it.

**Comment by norabelrose** [comment]
@anshradh Yeah if it's done by the end of the weekend that should be fine! Feel free to ping me on the eliciting-latent-knowledge channel of the Eleuther Discord with questions
