### ISSUE TITLE
Story cloze doesn't work anymore

### ISSUE THREAD

**Issue by FabienRoger** [EleutherAI/elk#69]
Story cloze needs local data to be loaded. Currently, only HF datasets stored by HF are usable.

**Comment by FabienRoger** [comment]
Note: story cloze needs special treatment for split, because if uses (validation, test) instead of (train, validation) or (train, test) (the only supported splits).

**Comment by norabelrose** [comment]
I'm against hardcoding _any_ datasets into the code but we should allow for local jsonl datasets and the like

**Comment by FabienRoger** [comment]
Agreed. My proposed fix would like
- if can't find on HF, try loading locally using an env variable
- if can't find "train" split, use "validation" and "test" split instead

**Comment by norabelrose** [comment]
Story cloze isn't worth supporting
