### ISSUE TITLE
Weights & Biases integration

### ISSUE THREAD

**Issue by norabelrose** [EleutherAI/elk#81]
Right now we store runs in `~/.cache/elk`, but arguably it would be better to integrate with Weights & Biases and treat the hidden states generated by `elk extract` as [Artifacts](https://docs.wandb.ai/guides/artifacts).

The main difficulty here is that we definitely don't want to force people to create W&B accounts in order to use the library. So the first step is to figure out whether we can still offload the local cache management to `wandb` without doing `wandb login`. If logging in is just required, it may turn out that W&B integration isn't worth it.

**Comment by derpyplops** [comment]
Why not offer both local and wandb caching?

**Comment by norabelrose** [comment]
This is not really needed
